### ISSUE TITLE
Position slider does not reset when starting playback of another item

### ISSUE THREAD

**Issue by fkuehne** [pdherbemont/Glasses#13]
When playing a list of items within a single document, the position slider won't reset when starting the next item. The time display is, though.

**Comment by pdherbemont** [comment]
I am investigating this, and I believe this is a WebKit bug a priori.

**Comment by schriftgestalt** [comment]
There is a general problem with the positioning of the slider. For me it is not updated at all. It can be used to jump in the movie (so it is somehow wired to the right property) but the update notification is missing.

**Comment by pdherbemont** [comment]
This is an other regression introduced by the bindings I am guessing. I will fix it at some point.

**Comment by pdherbemont** [comment]
(but not now)

**Comment by pdherbemont** [comment]
Should be fixed.
