### ISSUE TITLE
[PERF] Window resize time is still too slow using default style

### ISSUE THREAD

**Issue by pdherbemont** [pdherbemont/Glasses#14]
We need to make sure this can be rendered faster.

Investigate:
- Cache gradient and shadow,
- Report that CoreAnimation can be a bottleneck to Apple/WebKit.
- Remove CoreAnimation requirement from WebKit when there is no animation.

**Comment by pdherbemont** [comment]
Also, during benchmarking it occurs that resizing is actually faster when using a non-borderless window (!).

**Comment by pdherbemont** [comment]
- Non Opaque Window are slow
- CoreAnimation (ie, -webkit-transform-rotateY) is slow
- Rendering the gradient, border by hand is also a bit slow, we could use some caching there.

**Comment by CarterA** [comment]
CoreAnimation doesn't like transparency. Try to limit the transparent areas that are dealt with by CoreAnimations and you should be able to speed up scrolling. Also, limit the amount of subviews you have, try to draw directly into the view whenever possible.

**Comment by pdherbemont** [comment]
CoreAnimation should be fine with transparency, especially in WebKit, and, we don't have transparent region. (What makes you say that?). 
The number of views is not a bottleneck. either.

I have identified the bottlenecks (above), and I have fixed them locally. I need however one or two things to be done before pushing.

**Comment by pdherbemont** [comment]
This is fixed.
