### ISSUE TITLE
Window drawing problem when opening folders from splash page

### ISSUE THREAD

**Issue by CarterA** [pdherbemont/Glasses#15]
Here is what is happening:  http://c.zcr.me/6Hf2e

Looks like the backing window is getting drawn with the wrong style. I'm looking in to it.

Note:  This only happens when the Debug setting "Enable Styled Window Frame" is checked.

**Comment by pdherbemont** [comment]
This is actually the purpose of that debug setting. This is what happen in "real life", you are looking at the real NSWindow and its content... We could
probably make this more explicit.

**Comment by fkuehne** [comment]
Fixed by [90fe73781365bbbe6b1835325f1bf4c814737aa6]
