### ISSUE TITLE
Clicking in the progress bar area after a video is finished raises exception

### ISSUE THREAD

**Issue by jasonprado** [pdherbemont/Glasses#16]
Let a video finish playing, then the progress bar goes away and only the word 'Playing' remains. Click anywhere to the left of the word and an exception is raised:

2009-12-24 19:01:36.693 Lunettes[69968:a0f] **\* Exception Handled! LibVLCException: libvlc has thrown us an error: Input is NULL (/Users/jasonprado/src/vlc/projects/macosx/framework/Sources/VLCMediaPlayer.m:842 -[VLCMediaPlayer setPosition:])
NSExceptionHandlerExceptionRaiser (in ExceptionHandling) + 127
objc_exception_throw (in libobjc.A.dylib) + 45
**catch_exception (in VLCKit) (VLCLibrary.m:50)
-[VLCMediaPlayer setPosition:](in VLCKit) + 133
-[VLCStyledVideoWindowView setPosition:](in Lunettes) + 88
__invoking_** (in CoreFoundation) + 140
...

**Comment by jasonprado** [comment]
Should that area be unclickable when the video finishes? I'm brand new to Lunettes but I can contribute a patch here if I get some guidance.

**Comment by pdherbemont** [comment]
Hum... Thanks for the report!

This is actually a bug in VLCKit which should have --play-and-pause. I'll push a fix ASAP there.

But there is an underlying bug... The slider is not visible and thus shouldn't trigger any action.

**Comment by pdherbemont** [comment]
Would be awesome if you could contribute to lunettes with a patch for that issue or anything else :)

**Comment by pdherbemont** [comment]
The VLCKit issue should be fixed.
