### ISSUE TITLE
Opening folders results in an empty playlist

### ISSUE THREAD

**Issue by fkuehne** [pdherbemont/Glasses#17]
Opening folders (non-nested folders, just a single one with a few files in it) leads to an empty playlist. The window title still shows the number of items though and playback works nicely.

**Comment by pdherbemont** [comment]
can't reproduce here... Do you see a JS error or something?

**Comment by fkuehne** [comment]
Hmm, not exactly. The playlist shows an "undefined" entry now though. When double-clicking the entry, the following happens:

2009-12-28 01:09:42.759 Lunettes[34554:a0b] **\* Assertion failure in -[VLCWebBindingsController bindDOMObject:property:toObject:withKeyPath:], /Users/fpk/Desktop/videolan/Glasses/Sources/VLCWebBindingsController.m:222
2009-12-28 01:09:42.769 Lunettes[34554:a0b] **\* Exception Handled! NSInternalInconsistencyException: Binding of <DOMHTMLInputElement [INPUT]: 0x102df1a80 ''>.value already exists
NSExceptionHandlerExceptionRaiser (in ExceptionHandling) + 127
objc_exception_throw (in libobjc.A.dylib) + 45
+[NSException raise:format:arguments:](in CoreFoundation) + 103
-[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:](in Foundation) + 198
-[VLCWebBindingsController bindDOMObject:property:toObject:withKeyPath:](in Lunettes) (VLCWebBindingsController.m:224)
-[VLCStyledVideoWindowView bindDOMObject:property:toBackendObject:withKeyPath:](in Lunettes) (VLCStyledVideoWindowView.m:340)
**invoking_** (in CoreFoundation) + 140
-[NSInvocation invoke](in CoreFoundation) + 141
JSC::Bindings::ObjcInstance::invokeMethod(JSC::ExecState_, WTF::Vector<JSC::Bindings::Method_, 0ul> const&, JSC::ArgList const&) (in WebCore) + 787
JSC::callRuntimeMethod(JSC::ExecState_, JSC::JSObject_, JSC::JSValue, JSC::ArgList const&) (in WebCore) + 643
cti_op_call_NotJSFunction (in JavaScriptCore) + 478

**Comment by fkuehne** [comment]
Ah, it may be important that I'm opening the folder by dragging it to the icon in the Dock. You have to press the alternative-key to make it open of course, as a folder is no valid document type for Lunettes yet.

**Comment by pdherbemont** [comment]
ok. I reproduce now.

**Comment by pdherbemont** [comment]
works fine now. Close if it is fixed for you.

**Comment by fkuehne** [comment]
Works nicely. Thanks for fixing!
