### ISSUE TITLE
Multiple selection allowed between Collection Views on Splash Screens

### ISSUE THREAD

**Issue by CarterA** [pdherbemont/Glasses#18]
In the two collection views in the splash screen, you can select one item in each. When you hit open, it only opens the selected item in the library. I recommend we change it so that you can only have one global selection. Not sure how we'd do that.

**Comment by pdherbemont** [comment]
This is definitely a bug. (Side note: we have even more issues with the SplashScreen - scroll bar and such...)

**Comment by CarterA** [comment]
On the topic of the side note, I have actually been focussing on redesigning the splash screen. This is it so far...
http://c.zcr.me/80y6c
It is functional. Not yet complete, but functional. The layout is fluid, and can be resized and the split views can be adjusted.

**Comment by pdherbemont** [comment]
Seems pretty cool!

Do you think we can retain the header name? I am thinking about the Libraries part and the "Unfinished Movies" part. I think it makes more sense, especially when one of them is empty.

If you are at it, I'd like also to see drag and drop support in the Unfinished movies part.

**Comment by CarterA** [comment]
I'm still working out a way to implement headers, but they are definitely going to happen.

I will definitely go ahead and implement drag and drop as well.

**Comment by schriftgestalt** [comment]
The issue with the double selection and the header names would be solved with a tabview. Then you have only one of the two list visible at once.

**Comment by fkuehne** [comment]
Hmm, a tabview wouldn't be nice as the major advantage of this splash screen is to show both input variants side by side at the same time...

**Comment by pdherbemont** [comment]
I do agree with Felix.

We could however see it a bit more contextual, and show some kind of a tab view that would automatically make it obvious when there is an Unfinished movie.

That said, we are not on the iphone, and we do actually have some spaces on the screen. And current way of seeing both of them at the same time is very good to make the two features easily discoverable.

When drag and drop, and folder watch will be implemented, the Unfinished movie will probably play a more important role, and we'll have to mitigate this.

The selection issue is something relatively easy to fix and shouldn't drive that decision.

**Comment by schriftgestalt** [comment]
I did mockup in Photoshop:
www.schriftgestaltung.de/image/Lunettes-Splash-GS.png
It needs some more tweaking but it actually only a outlineview with a resemblance to the iTunes sidebar.
What do you think?

**Comment by CarterA** [comment]
I kind of like the concept, but I think that it is a poor use of screen real-estate. This isn't something that needs to fit in a sidebar, it should be able to utilize both horizontal and vertical screen space. Thus the two-column design.

In other news, I am fixing this in the patch I'm making for the splash screen, so don't fret about it any longer.

**Comment by schriftgestalt** [comment]
If you think as the splash screen as only the entry window. But it could serve as a meta playlist on the left side of the video window. Not that I would like it, but it serves the same functionality as the sidebar in iTunes.

**Comment by pdherbemont** [comment]
The UI mockup is looking nice! Yet, I do agree with Carter.

hmm. The splash screen doesn't belong to the Video Document window. I don't think it is something we want to go to.

However, we certainly want a splash screen for... Fullscreen. Would be great.

**Comment by fkuehne** [comment]
For fullscreen, I'd propose a HUD-styled window with basically the same options as the regular splash screen. This can be easily done once Carter's patch is merged.

**Comment by pdherbemont** [comment]
Carter, what is the status of this? Do you have something we could review or build on?

**Comment by CarterA** [comment]
Nothing complete yet, and for that I apologize. I ran into issues with resizing which prevented it from being nice at all, and I haven't been able to fix them yet.

**Comment by pdherbemont** [comment]
Do you happen to have something even non working? I am probably going to iterate on it.

**Comment by pdherbemont** [comment]
(In a repo or somewhere?)

**Comment by CarterA** [comment]
I just committed all my changes, no matter how strange they may be. Use it as you will:  CarterA/Glasses@262f4a267a10bbe16b04d98a5f97eb7c7bad1605

**Comment by pdherbemont** [comment]
Merged. Thanks Carter! (And fixed the multiple selection issue).

Feel free to reiterate on the look. A Master Detail View is ok for me.

Closing.
