### ISSUE TITLE
Install smart crash reports for crash reports.

### ISSUE THREAD

**Issue by pdherbemont** [pdherbemont/Glasses#19]
Install smart crash reports for crash reports.

**Comment by pdherbemont** [comment]
Or, the one we have in vlc.

**Comment by fkuehne** [comment]
I would prefer the existing solution, as smart crash reports install various ugly hacks to the OS to achieve its purpose.

**Comment by pdherbemont** [comment]
agreed.

**Comment by fkuehne** [comment]
added crash reporting facility. Closed by c67f902c9ea58e5f6743509263d8657c992dbd26
