### ISSUE TITLE
Stepping Back/forth with shortcut

### ISSUE THREAD

**Issue by schriftgestalt** [pdherbemont/Glasses#24]
If you hit Command+Left/Right, the video jumped 10 sec. This was just about right to go back if you missed a scene in the move. Now, if you hit left/right arrow key, it jumps 60 sec. This is a bit to much.

**Comment by pdherbemont** [comment]
Easy to fix I guess.

**Comment by fkuehne** [comment]
yep, it's a s/mediumJump_/shortJump_.

Done. Re-open if the new interval doesn't suit your needs either.
