### ISSUE TITLE
New Icon?

### ISSUE THREAD

**Issue by WilNichols** [pdherbemont/Glasses#32]
Well, as it seems to be a total revamp that is being attempted, why not have a new icon? I'd be more than willing to do it myself, I have a few ideas, in fact... This is the farthest-progressed of what I have thus far. http://drp.ly/9NKI

**Comment by pdherbemont** [comment]
It's looking great!

**Comment by pvinis** [comment]
I think it should have a bit of the orange cone somewhere somehow... don't you think?
nice work though

**Comment by pdherbemont** [comment]
orange would be nice.

**Comment by pdherbemont** [comment]
I know regular VLC developers tends to like the cone as well...

**Comment by pvinis** [comment]
why not take the cone and make it cocoa instead of orange :)

or change the shape. instead of a cone, it could be a diamond or something...

**Comment by mxcl** [comment]
The cone doesn't conform the the Apple UI guidelines, namely: ["[the application icon] should immediately convey the application’s purpose"](http://developer.apple.com/Mac/library/documentation/UserExperience/Conceptual/AppleHIGuidelines/XHIGIcons/XHIGIcons.html)

If the purpose of Lunettes is to fit well as a Mac application, then probably an icon like the (very good) proposal by WilNichols should be used.

However changing the icon should not be done lightly. Be sure of the new choice!

**Comment by pdherbemont** [comment]
Yes.

However the cone has become so popular that it now means video playing and VLC on every platform (_sigh_) ;-)

I think we have to keep a certain uniformity. Cone, stripes, orange. Some of them must be retained.

On the icon proposal, I feel like the musical note is not really appropriate. But I have to agree, it looks great. I'd love to see its small version as well.

**Comment by fkuehne** [comment]
I tend to agree with Pierre here, although Max is definitely right that VLC's icon doesn't confirm with Apple's icon guide lines (while having a look at my Dock right now, I'm noticing that few apps actually show what they are doing, especially Adode Reader, Adium and VMware Fusion are far from being obvious, but well known trademarks, which turn their icons obvious again).

Most of the time when I'm asked on what obscure French multimedia project I'm working on, I just say, well, it's the cone you or your significant other probably tend to play all your movies with. Therefore, it wouldn't be wise to drop it on the Mac. I'm fine with another variant, but the cone itself should be retained. In case some of you guys remember VLC's 0.6.0 icon, we did this before and it was okay.

**Comment by WilNichols** [comment]
Well, I can try to integrate the cone into another idea... I really do like the idea of a new icon though. It fits what is practically a rebrand of the app, and finally conforms to the HIG.

**Comment by pvinis** [comment]
You should look at this
http://uxmag.com/design/realism-in-ui-design
It says some interesting stuff about UI, and icons.
At the bottom, it has 3 icons. One is of coda, one of acorn, and the third is vlc's cone.
I think that answers the question if yo should change the icon altogether, or just spice it a little bit.

**Comment by WilNichols** [comment]
Well, tell me if this is better... It retains much of the cone's elements, but applies far better to the HIG.
http://drp.ly/skxbR

**Comment by pvinis** [comment]
I think its nice.

**Comment by dmehala** [comment]
Personally I think the icon of vlc is an element fundamental. Today much of anybody knows the small orange and white stud. Now, it is true that this version of vlc is (at least I hope) something moreover succeeded and who will mark a deep change, thus would the icon have to be changed? Not but to improve it and if possible refers to its possibilities without changing the icon too much.

**Comment by pvinis** [comment]
make it a white and orange barrel!

**Comment by WilNichols** [comment]
Could I get some type of official word on this? Until I know it will be used, I can't include it in a portfolio, or finish the remaining sizes.

**Comment by pdherbemont** [comment]
It's a pity to say, but the icon has to be a cone... Unless we change it on all platform. :/

**Comment by dmehala** [comment]
I think of dealing with the icon. ^^
@pdherbemont: ta pas reçu mon mail ?

**Comment by pdherbemont** [comment]
@DamiX hmm. nope.
