### ISSUE TITLE
Playlist + Close window

### ISSUE THREAD

**Issue by ponychicken** [pdherbemont/Glasses#34]
When u have a folder/m3u open, then close the window (command w) it will result in an exception message:

NSRangeException: Cannot remove an observer <NSKeyValueObservance 0x11275dde0> for the key path "media.@count" from <VLCMediaList 0x10052dda0> because it is not registered as an observer.

Back trace has been printed to Console.

We will now wait for debugger connection...

**Comment by pdherbemont** [comment]
Reproduced.

**Comment by fkuehne** [comment]
Works for me™
