### ISSUE TITLE
2 Interface bugs/improvements

### ISSUE THREAD

**Issue by ponychicken** [pdherbemont/Glasses#35]
1. The playlist doesn't autohide in Fullscreen
2. Suggestions: a. Make double click on video area result in fullscreen ( like dc in fs leaves fs)
   b) enable volume change with scrollwheel (like in vlc)

**Comment by pdherbemont** [comment]
Separate issue should be in separate issue :) thanks for the report. 2.a should work however :/

**Comment by pdherbemont** [comment]
Closing for cleanup, please reopen using different issues.
