### ISSUE TITLE
10.5 support

### ISSUE THREAD

**Issue by Zialus** [pdherbemont/Glasses#37]
http://img.skitch.com/20100118-m77dek8xscbehf34c87nyegxpd.jpg

**Comment by pdherbemont** [comment]
Seems like I broke 10.5 support on the way.

**Comment by Zialus** [comment]
?

I'm using 10.6 with xcode 3.2.1, just like the wiki asks to do

**Comment by pdherbemont** [comment]
The 10.5 sdk is being used here. I probably should change the base sdk in the meantime so that you don't get this error if you hit build.

Thanks!

**Comment by PacoBell** [comment]
When compiling VLCKit, I get "* VLC will be compiled in 64bit mode using the 10.5 SDK.        *" because of this:

```
if test $HAVE_DARWIN_64; then
     set +x
     echo
     echo "*****************************************************************"
     echo "* VLC will be compiled in 64bit mode using the 10.5 SDK.        *" 
     echo "*****************************************************************"
     set -x
fi
```

Is this normal?

**Comment by pdherbemont** [comment]
This is ok. Anyway, this one is a bug that belongs to VLC.

**Comment by fkuehne** [comment]
Fixed and confirmed to work.
