### ISSUE TITLE
Pressing the space key when playing a movie results in an error

### ISSUE THREAD

**Issue by fkuehne** [pdherbemont/Glasses#4]
$@

file:///Users/fpk/Desktop/videolan/Glasses/build/Debug/Lunettes.app/Contents/PlugIns/Default.lunettesstyle/Contents/Resources/%lunettes_style_root%/WindowController.js:207: JS ERROR: TypeError: Result of expression 'this.togglePlaying' [undefined] is not a function.

The respective code looks okay from what I can tell though.

**Comment by pdherbemont** [comment]
should be fixed. please close if verified.

**Comment by pdherbemont** [comment]
Style: Make sure we call keyDown with the right "this" value.

Closed by c1d3db312b27b4114eb7ddaea3154e1074cb2197.
