### ISSUE TITLE
Subtitle rendering

### ISSUE THREAD

**Issue by ponychicken** [pdherbemont/Glasses#40]
It seems that subtitle files are rendered in the resolution of the video. This leads to "blurry" looking fonts. Eg. if the video is 640x480 with an srt file, being watch fullscreen on a monitor with 1920x1080, the subtitle have the same resolution as if watched in a 640x480 window.

**Comment by pdherbemont** [comment]
This is a VLC Core limitation that may go away with 1.2 or whatever major release we see after 1.1.

We should keep a track of this bug on trac.videolan.org.

**Comment by ponychicken** [comment]
Could u fill the bug at the trac? I think registration are closed

**Comment by pdherbemont** [comment]
Trac registration is not closed. You need to get your account approved on IRC as explained there.

I think that if you google the right terms you should be able to find an existing ticket for that anyway.

**Comment by fkuehne** [comment]
This is probably covered by the vout rework ticket, which also speaks about the impossibility of moving the subtitles out of the video's screen area aka in to the black border.

**Comment by pdherbemont** [comment]
Closing.
