### ISSUE TITLE
Compilation error under Snow Leopard with XCode 3.2.1

### ISSUE THREAD

**Issue by kwin** [pdherbemont/Glasses#41]
I get the following error (Base SDK 10.6, Debug Snow Leopard, I386):

<pre>
CompileC build/Lunettes.build/Debug/Lunettes.build/Objects-normal/i386/VLCSplashScreenWindowController.o Sources/VLCSplashScreenWindowController.m normal i386 objective-c com.apple.compilers.llvmgcc42
cd /Users/kwindszus/Sourcecode/VLC/Glasses
setenv LANG en_US.US-ASCII
/Developer/usr/bin/llvm-gcc-4.2 -x objective-c -arch i386 -fmessage-length=0 -pipe -std=gnu99 -Wno-trigraphs -fpascal-strings -fasm-blocks -O0 -Werror -Wmissing-prototypes -Werror-implicit-function-declaration -Wreturn-type -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wunused-label -Wunused-variable -Wunused-value -Wunknown-pragmas -Wfour-char-constants -Wsign-compare -Wnewline-eof -Wundeclared-selector -isysroot /Developer/SDKs/MacOSX10.6.sdk -mfix-and-continue -mmacosx-version-min=10.6 -gdwarf-2 -iquote /Users/kwindszus/Sourcecode/VLC/Glasses/build/Lunettes.build/Debug/Lunettes.build/Lunettes-generated-files.hmap -I/Users/kwindszus/Sourcecode/VLC/Glasses/build/Lunettes.build/Debug/Lunettes.build/Lunettes-own-target-headers.hmap -I/Users/kwindszus/Sourcecode/VLC/Glasses/build/Lunettes.build/Debug/Lunettes.build/Lunettes-all-target-headers.hmap -iquote /Users/kwindszus/Sourcecode/VLC/Glasses/build/Lunettes.build/Debug/Lunettes.build/Lunettes-project-headers.hmap -Wall -W -Wextra -Werror -Wcast-align -Wchar-subscripts -Wformat-security -Wmissing-format-attribute -Wpointer-arith -Wwrite-strings -Wno-format-y2k -Wno-unused-parameter -Wbad-function-cast -Wmissing-declarations -Wnested-externs -F/Users/kwindszus/Sourcecode/VLC/Glasses/build/Debug -F/Users/kwindszus/Sourcecode/VLC/Glasses/build/Debug/Lunettes.app/Contents/Frameworks -F/Users/kwindszus/Sourcecode/VLC/Glasses -F/Developer/SDKs/MacOSX10.6.sdk/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks "-F/Users/kwindszus/Sourcecode/VLC/Glasses/../../../Development/Mac/BWToolkit 1.2.2" -I/Users/kwindszus/Sourcecode/VLC/Glasses/build/Debug/include -I/Users/kwindszus/Sourcecode/VLC/Glasses/build/Lunettes.build/Debug/Lunettes.build/DerivedSources/i386 -I/Users/kwindszus/Sourcecode/VLC/Glasses/build/Lunettes.build/Debug/Lunettes.build/DerivedSources -isysroot /Developer/SDKs/MacOSX10.6.sdk -include /var/folders/-g/-gYUzHJpFrCaxgtDj9scIE+++TI/-Caches-/com.apple.Xcode.501/SharedPrecompiledHeaders/VLC_Prefix-cekhjtdlyphvcddxwadijjgttepd/VLC_Prefix.pch -c /Users/kwindszus/Sourcecode/VLC/Glasses/Sources/VLCSplashScreenWindowController.m -o /Users/kwindszus/Sourcecode/VLC/Glasses/build/Lunettes.build/Debug/Lunettes.build/Objects-normal/i386/VLCSplashScreenWindowController.o

/Users/kwindszus/Sourcecode/VLC/Glasses/Sources/VLCSplashScreenWindowController.m:36: error: synthesized property 'hasSelection' must either be named the same as a compatible ivar or must explicitly name an ivar
</pre>

**Comment by PacoBell** [comment]
Ditto. =(

**Comment by pdherbemont** [comment]
arg. I let that goes along. This is using a specific Objective-C runtime feature only available on x86_64.

I'll try to fix that.

**Comment by pdherbemont** [comment]
Should be fixed.

**Comment by kwin** [comment]
Unfortunately there is a typo in the git commit. In the header the variable hasSelection has one leading underscore, in the implementation it has two. Both should obviously have identical names, otherwise compilation will fail with the same error.

**Comment by pdherbemont** [comment]
Thanks.
