### ISSUE TITLE
Support for different container formats like mkv

### ISSUE THREAD

**Issue by gmthor** [pdherbemont/Glasses#42]
I wrote an email to pdherbmont to ask what to to to enable playback for mkv video files. And he said that it is probably only editing the Info.plist file.
It didn't work for me though.
Any idea?

**Comment by pdherbemont** [comment]
Should be fixed for .mkv. Please do the same for any container you think we should support.

**Comment by gmthor** [comment]
Looks simple.
Just one question.
Is the UTTypeIdentifier arbitrary and only needs to be the same as in the beginning of the file or is the name come from the Mac OS X API?
The key "org.matroska.video" just doesn't look random and I want to know if it is your naming convention oder from somewhere else.

**Comment by pdherbemont** [comment]
Generally use the reverse domain name of the company. I can't find the actual paper from Apple about UTI.

**Comment by fkuehne** [comment]
Closing as this appears to be fixed. Please open new tickets in case other file formats need to be added to the plist.
