### ISSUE TITLE
Theme switching results in disabled menu bar items.

### ISSUE THREAD

**Issue by gmthor** [pdherbemont/Glasses#44]
I switched to the style black but now the style menu is grey and i can't switch to another style back.

**Comment by gmthor** [comment]
OK I figured out why it happens.
If I want to switch the style I do the following.
I want to get the focus of the currently playing video. I do this by clicking on the top bar ( the bar that hast the red/yellow/green button on the left)
Then I go to view->style and there all options are grey ( not selectable ).

To be able to switch I actually need to click inside the window where the video is playing and if I go to the menu now, all options are selectable.

Does that make sense?

**Comment by pdherbemont** [comment]
Yes, that's a bug.

**Comment by pdherbemont** [comment]
VLCStyledVideoWindowView: Make sure we are the initial first responder.

Closed by 3ea7bc55e19a79dbec8a4a2fb9df12f657ac3a16.

**Comment by pdherbemont** [comment]
Should be fixed Thanks!
