### ISSUE TITLE
Program received signal:  “EXC_BAD_INSTRUCTION”.

### ISSUE THREAD

**Issue by gmthor** [pdherbemont/Glasses#45]
I have got vlc-lib and Lunettes up to date. When I try play any media I get this error.
Program received signal:  “EXC_BAD_INSTRUCTION”.
I know that this happens in a function of the VLCKit but i believe that I started getting this error after some changes in the Lunettes project where made.

If your sure that it's not a bug in Lunettes i'll post it on the vlc-devel mailinglist.

ERROR in: fastmemcpy.h
# ifndef HAVE_SSE

```
    /* enables to use FPU */
    __asm__ __volatile__ (EMMS:::"memory");
```
# endif

gdb bt
#0  fast_memcpy () at fastmemcpy.h:375
#1  0x00000001001c810a in vlc_memcpy () at cpu.c:360
#2  0x00000001136f138f in DecodeVideo () at vlc_block.h:165
#3  0x0000000100188370 in DecoderDecodeVideo () at vlc_block.h:165
#4  0x00000001001877d3 in DecoderProcess () at decoder.c:1818
#5  0x0000000100186b8d in DecoderThread () at decoder.c:867
#6  0x00000001001c6c6e in thread_entry () at threads.c:58
#7  0x00007fff88121f8e in _pthread_start ()
#8  0x00007fff88121e41 in thread_start ()

**Comment by gmthor** [comment]
fixed with the latest vlc-lib commit

**Comment by pdherbemont** [comment]
Cool.
