### ISSUE TITLE
splash screen enhancement #1

### ISSUE THREAD

**Issue by gmthor** [pdherbemont/Glasses#46]
Quite often I watch movies that have a very long filename and at the end of it is the chapter number.
So it doesn't really help to see the beginning of the filename.

One possible solution would be to show the complete filename if you wait with your curser above it for some time. Like in the Program AdiumX when you wait with your curser above a contact until his info pops up.

**Comment by pdherbemont** [comment]
This is something wanted yes. Someone willing to step in?

**Comment by CarterA** [comment]
I'm working on it, should be committed as soon as I can get VLCKit working.

**Comment by CarterA** [comment]
Change is available here:  CarterA/Glasses@1a652c5c1cd809b53bbd1c768619610dae6e34bf

**Comment by pdherbemont** [comment]
Applied, thanks Carter!
