### ISSUE TITLE
Lunettes crashes when EyeTV is installed

### ISSUE THREAD

**Issue by Poopi** [pdherbemont/Glasses#49]
Lunettes crashes when EyeTV is installed with log:
10-02-03 22:43:55   Lunettes[18283] **\* Exception Handled! LibVLCException: libvlc has thrown us an error: upnp_intel: internal module error (/Users/steg/Sources/vlc/projects/macosx/framework/Sources/VLCMediaDiscoverer.m:99 -[VLCMediaDiscoverer initWithName:])
10-02-03 22:43:55   Lunettes[18283] Error loading /Library/ScriptingAdditions/Adobe Unit Types.osax/Contents/MacOS/Adobe Unit Types:  dlopen(/Library/ScriptingAdditions/Adobe Unit Types.osax/Contents/MacOS/Adobe Unit Types, 262): no suitable image found.  Did find:
    /Library/ScriptingAdditions/Adobe Unit Types.osax/Contents/MacOS/Adobe Unit Types: no matching architecture in universal wrapper
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] Lunettes: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/Adobe Unit Types.osax" declares no loadable handlers.
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] NSExceptionHandlerExceptionRaiser (in ExceptionHandling) + 127
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] objc_exception_throw (in libobjc.A.dylib) + 45
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] __catch_exception (in VLCKit) + 318
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] -[VLCMediaDiscoverer initWithName:](in VLCKit) + 368
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] +[VLCMediaDiscoverer availableMediaDiscoverer](in VLCKit) + 665
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] -[VLCSplashScreenWindowController availableMediaDiscoverer](in Lunettes) + 55
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] -[NSObject(NSKeyValueCoding) valueForKey:](in Foundation) + 420
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] -[NSObject(NSKeyValueCoding) valueForKeyPath:](in Foundation) + 226
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] -[NSBinder valueForBinding:resolveMarkersToPlaceholders:](in AppKit) + 171
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] -[NSArrayDetailBinder _refreshDetailContentInBackground:](in AppKit) + 368
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] -[NSObject(NSKeyValueBindingCreation) bind:toObject:withKeyPath:options:](in AppKit) + 557
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] -[NSIBObjectData nibInstantiateWithOwner:topLevelObjects:](in AppKit) + 1172
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] loadNib (in AppKit) + 226
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] +[NSBundle(NSNibLoading) _loadNibFile:nameTable:withZone:ownerBundle:](in AppKit) + 248
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] -[NSWindowController loadWindow](in AppKit) + 233
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] -[NSWindowController window](in AppKit) + 82
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] -[NSWindowController showWindow:](in AppKit) + 47
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] -[VLCDocumentController applicationDidFinishLaunching:](in Lunettes) + 418
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] _nsnote_callback (in Foundation) + 167
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] __CFXNotificationPost (in CoreFoundation) + 954
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] _CFXNotificationPostNotification (in CoreFoundation) + 200
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] -[NSNotificationCenter postNotificationName:object:userInfo:](in Foundation) + 101
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] -[NSApplication _postDidFinishNotification](in AppKit) + 100
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] -[NSApplication _sendFinishLaunchingNotification](in AppKit) + 66
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] -[NSApplication(NSAppleEventHandling) _handleAEOpen:](in AppKit) + 219
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:](in AppKit) + 77
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:](in Foundation) + 360
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] _NSAppleEventManagerGenericHandler (in Foundation) + 114
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] aeDispatchAppleEvent(AEDesc const_, AEDesc_, unsigned int, unsigned char_) (in AE) + 162
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] dispatchEventAndSendReply(AEDesc const_, AEDesc*) (in AE) + 32
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] aeProcessAppleEvent (in AE) + 210
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] AEProcessAppleEvent (in HIToolbox) + 48
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] _DPSNextEvent (in AppKit) + 1191
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:](in AppKit) + 155
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] -[NSApplication run](in AppKit) + 395
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] NSApplicationMain (in AppKit) + 364
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] main (in Lunettes) + 37
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] start (in Lunettes) + 52
10-02-03 22:43:55   [0x0-0x37e37e].org.videolan.Lunettes[18283] 0x00000002 (in Lunettes)
10-02-03 22:44:06   com.apple.launchd.peruser.502[570]([0x0-0x37e37e].org.videolan.Lunettes[18283]) Job appears to have crashed: Abort trap
10-02-03 22:44:06   ReportCrash[18289]  Saved crash report for Lunettes[18283] version 1.0 Beta (3.0) to /Users/poopiroot/Library/Logs/DiagnosticReports/Lunettes_2010-02-03-224406_Mac-Printer-2.crash
Thee seems to be a proem with PnP EyeConect server (part of EyeTV package).
Killing following processes helped:
1. /Library/Application Support/EyeTV/EyeTV Helper.app/Contents/MacOS/EyeTV Helper -psn_0_98328
2. /Library/Application Support/EyeConnect/EyeConnect.app/Contents/Resources/EyeConnectWatchDog
3. /Library/Application Support/EyeConnect/EyeConnect.app/Contents/MacOS/EyeConnect -console

**Comment by pdherbemont** [comment]
Seems like a bug in vlc's upnp. This will not crash in future release.

**Comment by crami** [comment]
I have the same problem here. When does a fixed release come out ?

**Comment by fkuehne** [comment]
There is no fixed date. Be assured that this will be fixed once we do a public beta release of Lunettes.

**Comment by fkuehne** [comment]
uhm, which EyeTV version are you guys using to trigger this issue please?

**Comment by Poopi** [comment]
Mine is 3.3 Build 5849

**Comment by Poopi** [comment]
But please turn on the DLNA server first. Go to preferences -> Sharing and tick " Share my EyeTV Archive" option.

**Comment by pdherbemont** [comment]
This should be fixed. Is it not?
