### ISSUE TITLE
[Feature] Flag 

### ISSUE THREAD

**Issue by dmehala** [pdherbemont/Glasses#51]
Flag is a new function which will be to implement in vlc glasses, here is a description rather detailed of its operation and these functionality.

Fonctionnality of Flag :
- To make it possible to return has one precise moment of a video/to define a video sequence (beginning-end). (principal function)
- To handle the Flags (To move, remove).
- Locking/Unlocking of a Flag.
- To record its Flags.

How to : (:p)
- Add a flag : - To one precise moment : one clicks left on the icon (http://img97.imageshack.us/img97/9735/flagfv.png).
                   - To a video sequence : two clicks left on the icon.
- To handle : - To move : one clicks left inserted on a flag and to move in the bar of reading.
                  -  To delete : one clicks left inserted and placement of the flag out of the bar of reading.
- Locking/Unlocking : - one clicks right on a flag.
- Recording : Click left on the small cursor (normally located on the right of the icon) and to choose “To record”.

(sorry I am french and I use a translator)

**Comment by fkuehne** [comment]
uhm, are you going to implement that? Will this make use of the existing recording architecture in VLC?

**Comment by dmehala** [comment]
No ^^, it is pdherbemont which will take care there, Thus I do not have any idea. I did to nothing but subject the idea him (by e-mail) and it has to find it good like feature

**Comment by fkuehne** [comment]
ah, alright :)

**Comment by pdherbemont** [comment]
That said, I think this is very similar to the Bookmark feature. I think we should merge the two tickets. And I kind of lack time to implement this...
