### ISSUE TITLE
Switching back to trac?

### ISSUE THREAD

**Issue by pdherbemont** [pdherbemont/Glasses#54]
Felix? Others? What do you think?

Now that trac is fixed on videolan, should we attempt to gradually move back there? The github facility is nice but lack milestones support and such.

**Comment by fkuehne** [comment]
I support that. I'll Lunettes and the macosx dialog provider as new components. Note that I already renamed the existing "Mac OS X Interface" to "Legacy Mac OS X Interface". Therefore, all of its issues won't interfere with this re-write.

Using trac on videolan will it also make a lot easier for us to track libvlc and core issues.

**Comment by pdherbemont** [comment]
ok. So time to start the move. I guess step one is to close all the ticket and say that we have moved to trac. And probably replace it in the doc as well.

**Comment by knoopx** [comment]
replace github for trac?:S

**Comment by bitsnlenses** [comment]
are all bugs now being reported in trac?

**Comment by fkuehne** [comment]
We accept new issues both here and on trac. However, Lunettes isn't actively developed at the moment, since its underlying code went into VLC's iOS port.
VLC 1.2 will include a re-vamped user interface for the Mac, which is inspired by Lunettes.
