### ISSUE TITLE
Option To Select Media Folder Path Other Than Default Location

### ISSUE THREAD

**Issue by SnidelyW** [pdherbemont/Glasses#57]
As I shared with Felix and Pierre via email, many people -- such as myself -- store media files in other locations, such as on external USB drives. Lunettes really needs an option which will allow the user to set the main media folder to a path and location of their choice. Being forced to use the main "Movies" folder is very limiting.

**Comment by fkuehne** [comment]
There are options to add custom search folders available in Lunettes' preferences now.

**Comment by SnidelyW** [comment]
Yes, I know. Thanks for your hard work! :)

Please see my other comment regarding listing folders and files in Lunettes' main window in multi-column Finder mode. Thanks!
