### ISSUE TITLE
Audio Gain Booster

### ISSUE THREAD

**Issue by SnidelyW** [pdherbemont/Glasses#59]
One nice feature that Chroma Player has is an audio gain booster. I can personally testify that for media files that have a low audio volume -- particular with vocals -- Chroma Player's audio gain booster does wonders. I highly recommend that this feature be added to Lunettes.

**Comment by fkuehne** [comment]
Should be part of the Equalizer panel.

**Comment by SnidelyW** [comment]
Wonderful! Can you estimate when this might be implemented? AFAIK, Chroma Player is currently the only Mac video player that I am aware of that has this feature.
