### ISSUE TITLE
Video window doesn't behave "correctly"

### ISSUE THREAD

**Issue by fkuehne** [pdherbemont/Glasses#6]
1) You can move the video window behind the menu-bar. According to Apple's HIG, the window's top position should be just below the menu-bar, so you can't move any window higher than the top-most centimeter.

2) The window doesn't adapt itself to the video size with the Default style. An HD video is opened with almost the same size as regular sized clips.

**Comment by pdherbemont** [comment]
1) Will do.
2) I don't particularly like the idea of resizing the window. Mostly for some technical reason, of the vout taking some times to know it size. I will investigate. Should we open a new ticket?

**Comment by pdherbemont** [comment]
Make sure we don't go beyond the menu bar when moving the window.

Closed by 2ed075c0c98d4f70c5f0b705b58074e2dedc8b3d.

**Comment by pdherbemont** [comment]
1) Fixed in 2ed075c0c98d4f70c5f0b705b58074e2dedc8b3d
