### ISSUE TITLE
Add Lunettes To VersionTracker & Other Mac Software Sites

### ISSUE THREAD

**Issue by SnidelyW** [pdherbemont/Glasses#61]
I think it would great if you guys added Lunettes to VersionTracker and other Macintosh software-related sites, such as MacUpdate, Mac.MajorGeeks.com, Tucows, Softpedia, etc. Not only will it increase interest in Lunettes, but you will gain more support, get more feedback, and possibly even some new Xcoders for Lunettes. Only the actual developers can add software to such sites, so I can't do it for you...or else I would.  ;)

**Comment by fkuehne** [comment]
Please refrain from adding Lunettes to these pages for now. There is no official release of this project as of yet which is also why it is still known by its codename. We will definitely put it on these pages once it is actually released.

**Comment by SnidelyW** [comment]
Don't worry, I won't. As I said above "Only the actual developers can add software to such sites, so I can't do it for you."  :)
