### ISSUE TITLE
Command Not Found: git describe --always

### ISSUE THREAD

**Issue by SnidelyW** [pdherbemont/Glasses#69]
I just updated my "vlc" directory to the latest code base. While Lunettes succeeds in building, it is throwing me one error which says "Command Not Found: git describe --always". Just thought you'd like to know. BTW, I also just updated Xcode to 3.2.2.

**Comment by fkuehne** [comment]
This is a known issue within the mainline VLC branch and is already covered by a trac ticket over there. Thanks for mentioning, though! :)
