### ISSUE TITLE
[PATCH] master doesn't build

### ISSUE THREAD

**Issue by giskarda** [pdherbemont/Glasses#74]
Latest xcode, latest git version (29 june), i had to cast for compile glasses :)

simple (and i think wrong way) patch:

diff --git a/Sources/VLCDocumentController.m b/Sources/VLCDocumentController.m
index 0209498..4387858 100644
--- a/Sources/VLCDocumentController.m
+++ b/Sources/VLCDocumentController.m
@@ -82,7 +82,7 @@

```
 CFIndex index = CFArrayBSearchValues((CFArrayRef) schemes, CFRangeMake(0, CFArrayGetCount((CFArrayRef)schemes)) , 
                                  (CFStringRef) scheme, (CFComparatorFunction)CFStringCompare, nil);
```
-    if ((index < [schemes count]) && [[schemes objectAtIndex:index] isEqualToString:scheme]) {
-    if (((unsigned long)index < [schemes count]) && [[schemes objectAtIndex:index] isEqualToString:scheme]) {
       return @"VLCMediaDocument";
   }
   NSRunCriticalAlertPanel(@"Lunettes does not support this protocol",

**Comment by pdherbemont** [comment]
Thanks! Please send a pull request :)

**Comment by giskarda** [comment]
Done :) please review it :)
