### ISSUE TITLE
Crash of Lunettes

### ISSUE THREAD

**Issue by lambourg** [pdherbemont/Glasses#79]
It seems I added some files to my Movies directory that made Lunettes crash systematically.

To investigate, I built Lunettes, debugged it and could find the issue. It's in VLCTitleDecrapifier.m, and the issue is simply a null pointer issue. My patch follows:

diff --git a/Sources/VLCTitleDecrapifier.m b/Sources/VLCTitleDecrapifier.m
index d76133c..3bdafcf 100644
--- a/Sources/VLCTitleDecrapifier.m
+++ b/Sources/VLCTitleDecrapifier.m
@@ -64,6 +64,8 @@ static inline NSNumber *numberFromTwoChars(char high, char low)
 {
     const char *str = [[string lowercaseString] UTF8String];
-       if (str == nil) return nil;
-   
   // Search for s01e10.
   for (unsigned i = 0; str[i]; i++) {
       if (str[i] == 's' &&

**Comment by fkuehne** [comment]
Fixed in the current code base. Thanks for the report!
