### ISSUE TITLE
We should support Window On Top for the Video Window.

### ISSUE THREAD

**Issue by pdherbemont** [pdherbemont/Glasses#8]
We should support Window On Top for the Video Window.

**Comment by CarterA** [comment]
Do you mean a floating window? "Always on top" behavior? If so, I can implement this.

**Comment by pdherbemont** [comment]
Yes, that what this means :)

**Comment by CarterA** [comment]
Added!

CarterA/Glasses@c08d82477fb6b7271112ac92cfa869db5d6db38d

**Comment by fkuehne** [comment]
I had to merge this patch manually because of conflicts in the xib file. While I was at it, I slightly changed your method to be called by the First Responder instead of calling the StyledWindowController directly.

Thanks for the patch!
