### ISSUE TITLE
Multiple instances when opening multiple files

### ISSUE THREAD

**Issue by nickkirby** [pdherbemont/Glasses#80]
Hello, might be an unreasonable request - is it possible to have Lunette open a new instance of itself whenever a new file is opened? Perhaps this could be a preferences option?

**Comment by fkuehne** [comment]
This does not comply with the way applications work on the Mac, so we won't do this. Lunettes allows you to open multiple files at a time though (in contrast to the traditional VLC). You can still open multiple instances using the Terminal or by creating multiple copies of Lunettes, but this may lead to conflicts and is therefore unsupported.
